### ISSUE TITLE
App Crashes on Selecting Camera Icon

### ISSUE THREAD

**Issue by siddh1004** [NAXAM/imagepicker-android-binding#1]
I'm using Naxam image picker in my android app. Its working fine on selecting images from gallery but when I click the camera icon , the app crashes. I can't find the reason why it's happening.I have given all the required permissions in Manifest file.OnActivityResult is also not called.
![git_namax](https://user-images.githubusercontent.com/25721637/30168686-c1cc02ae-9407-11e7-9ba2-050002deac3b.png)

**Comment by tuyen-vuduc** [comment]
@siddh1004 Plz check out latest binding [here](https://www.nuget.org/packages/Com.Github.Nguyenhoanglam.ImagePicker). Raise a new issue if it perists.
