### ISSUE TITLE
Please update to 1.2.0

### ISSUE THREAD

**Issue by MileyHollenberg** [NAXAM/imagepicker-android-binding#2]
1.2.0 has been released just 9 days ago but it includes a feature which I need to use (setting the color of the header bar). I tried to update the binding library myself by including the 1.2.0 aar but I'm getting loads of issues with it not being able to find certain references and thus not building the project.

**Comment by morejump** [comment]
@zezioen I'm currently binding for glide version 4.0 to update this library to 1.2.0, just waiting a few days.

**Comment by tuyen-vuduc** [comment]
@zezioen We have tried to update the binding; however, it depends on Glide which is out of date by now. It really takes time to get Glide update to v4x.

**Comment by morejump** [comment]
@zezioen  Now, i can use imagepicker version 1.2.0 and  I also added sample to the solution.  Thanks
