### ISSUE TITLE
Updating to 1.2.1

### ISSUE THREAD

**Issue by MileyHollenberg** [NAXAM/imagepicker-android-binding#3]
I requested a new feature in the base library which was added and put into 1.2.1 (https://github.com/nguyenhoanglam/ImagePicker/issues/80)

I tried to upgrade the binding library and it build successfully but when I try to use the new setKeepScreenOn() builder method it doesn't seem to recognize it. 

My updated code is forked here https://github.com/zezioen/imagepicker-android-binding, I haven't created a pull request yet since it doesn't fully function

**Comment by tuyen-vuduc** [comment]
@MileyHollenberg Please try the latest binding [here](https://www.nuget.org/packages/Com.Github.Nguyenhoanglam.ImagePicker).
