### ISSUE TITLE
NullPointerException on Start()

### ISSUE THREAD

**Issue by VeneetReddyK** [NAXAM/imagepicker-android-binding#4]
**Version:** 1.2.0

**Phone:** OnePlus One(A0001)
**Android version:** 6.0.1
**CyanogenMod API Level:** Elderberry(5)

**Code used:**
```
new ImagePicker.ActivityBuilder(activity)
               .SetFolderMode(true)
               .Start();
```

**Stack-trace:**
> ava.Lang.RuntimeException: Unable to start activity ComponentInfo{com.pyramid.app/com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nguyenhoanglam.imagepicker.widget.ProgressWheel.setBarColor(int)' on a null object reference ---> Java.Lang.NullPointerException: Attempt to invoke virtual method 'void com.nguyenhoanglam.imagepicker.widget.ProgressWheel.setBarColor(int)' on a null object reference
>   at java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nguyenhoanglam.imagepicker.widget.ProgressWheel.setBarColor(int)' on a null object reference
>   at at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.setupView(ImagePickerActivity.java:124)
>   at at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.java:106)
>   at at android.app.Activity.performCreate(Activity.java:6251)
>   at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
>   at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
>   at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
>   at at android.app.ActivityThread.-wrap11(ActivityThread.java)
>   at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
>   at at android.os.Handler.dispatchMessage(Handler.java:102)
>   at at android.os.Looper.loop(Looper.java:148)
>   at at android.app.ActivityThread.main(ActivityThread.java:5461)
>   at at java.lang.reflect.Method.invoke(Native Method)
>   at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>   at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>   --- End of inner exception stack trace ---
>   at java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pyramid.app/com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nguyenhoanglam.imagepicker.widget.ProgressWheel.setBarColor(int)' on a null object reference
>   at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
>   at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
>   at at android.app.ActivityThread.-wrap11(ActivityThread.java)
>   at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
>   at at android.os.Handler.dispatchMessage(Handler.java:102)
>   at at android.os.Looper.loop(Looper.java:148)
>   at at android.app.ActivityThread.main(ActivityThread.java:5461)
>   at at java.lang.reflect.Method.invoke(Native Method)
>   at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>   at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>   at Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nguyenhoanglam.imagepicker.widget.ProgressWheel.setBarColor(int)' on a null object reference
>   at at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.setupView(ImagePickerActivity.java:124)
>   at at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.java:106)
>   at at android.app.Activity.performCreate(Activity.java:6251)
>   at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
>   at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
>   at ... 9 more

Works fine on a Nexus 5 emulator with API level 27.

**Comment by tuyen-vuduc** [comment]
Plz check out the latest binding [here ](https://www.nuget.org/packages/Com.Github.Nguyenhoanglam.ImagePicker)and open a new issue if it persists.
