### ISSUE TITLE
It doesn't work with Android 13 due to permissions

### ISSUE THREAD

**Issue by ClarenceMG** [NAXAM/imagepicker-android-binding#5]

**Comment by tuyen-vuduc** [comment]
Probably an update is required. Which .NET frameworks are you targeting?

**Comment by ClarenceMG** [comment]
> Probably an update is required. Which .NET frameworks are you targeting?

@tuyen-vuduc I'm using Xamarin.Android Version: 13.2.2.0, my target Framework is Android 13.
This doesn't work because now in Android 13 the permission to access the gallery is ReadMediaImages, and the library uses WriteExternalStorage and ReadExternalStorage.
Are you planning to update the library?

**Comment by tuyen-vuduc** [comment]
.NET8 removes its build capability to the lower framework (monandroid, .NET6), then it's a barrier. 

To build the library to support those legacy ones, we have to remove .NET8 installation :D .

**Comment by tuyen-vuduc** [comment]
@ClarenceMG You can try the latest binding [here](https://www.nuget.org/packages/Com.Github.Nguyenhoanglam.ImagePicker).
